export const data = [
  {
    name: "EUROLINE 810 POP UP 700 W Pop Up Toaster  (White)",
    productId: "EURO19938201",
    brandName: "EUROLINE",
    category: "Pop Up Toasters",
    companyAssured: false,
    rating: "4.2",
    price: "12232",
    discount: "50%",
    imageURL:
      "https://rukminim1.flixcart.com/image/416/416/k5lcvbk0/pop-up-toaster/2/j/w/euroline-820-pop-up-810-pop-up-original-imafz8h3duveqgh7.jpeg?q=70",
    sellerName: "telform inc.",
    isNewProduct: true,
  },
  {
    name: "Morphy Richards 25 L Convection Microwave Oven  (MWO 25CG, Steel)",
    productId: "EURO19938202",
    brandName: "Morphy",
    category: "Microwave Ovens",
    companyAssured: true,
    rating: "3.9",
    price: "10999",
    discount: "11%",
    imageURL:
      "https://rukminim1.flixcart.com/image/416/416/microwave-new/v/q/y/morphy-richard-25cg-original-imaec2ddymudmze3.jpeg?q=70",
    sellerName: "Kwitch Retails",
    isNewProduct: false,
  },
  {
    name: "Fitbit Inspire 2  (Desert Rose Strap, Size : Regular)",
    productId: "EURO19938203",
    brandName: "Fitbit",
    category: "Smart Bands",
    companyAssured: true,
    rating: "3.9",
    price: "17992",
    discount: "",
    imageURL:
      "https://rukminim1.flixcart.com/image/416/416/khmbafk0/smart-band-tag/u/z/6/no-yes-fb418bkcr-android-ios-fitbit-yes-original-imafxhe4ff7ys5bc.jpeg?q=70",
    sellerName: "RetailNet",
    isNewProduct: true,
  },
  {
    name: "OnePlus 10R 5G (Forest Green, 8GB RAM, 128GB Storage, 80W SuperVOOC)",
    productId: "B09WRMNJ9G",
    brandName: "OnePlus",
    category: "Smartphone",
    companyAssured: true,
    rating: "4.2",
    price: "40000",
    discount: "",
    imageURL: "https://m.media-amazon.com/images/I/716uVx3Wr5L._SL1500_.jpg",
    sellerName: "RetailNet",
    isNewProduct: true,
  },
  {
    name: "Skechers Women's Skech-air Stratus-Wind Breeze Sneakers",
    productId: "efeffwgwrggwg",
    brandName: "Skechers",
    category: "Footwear",
    companyAssured: true,
    rating: "4.5",
    price: "4000",
    discount: "10%",
    imageURL: "https://m.media-amazon.com/images/I/814oKz2vZ2L._UL1500_.jpg",
    sellerName: "RetailNet",
    isNewProduct: true,
  },
  {
    name: "Crucial P5 Plus 500GB PCIe 4.0 3D NAND NVMe M.2 SSD, up to 6600MB/s - CT500P5PSSD8",
    productId: "efwefefewf",
    brandName: "Crucial",
    category: "Computers & Accessories",
    companyAssured: true,
    rating: "4.7",
    price: "14000",
    discount: "50%",
    imageURL: "https://m.media-amazon.com/images/I/418VuyafoUL._SL1075_.jpg",
    sellerName: "RetailNet",
    isNewProduct: true,
  },
  {
    name: "Mi Notebook Ultra 3.2K Resolution Display Intel Core I5-11300H 11Th Gen 15.6 Inches Thin Light Laptop(16Gb/512Gb Ssd/Iris Xe Graphics/Windows 11 Home/Ms Office 21/Backlit Kb/Fingerprint Sensor/1.7Kg)",
    productId: "efefefeffwww",
    brandName: "Mi",
    category: "Computers & Accessories",
    companyAssured: true,
    rating: "3.9",
    price: "75000",
    discount: "25%",
    imageURL: "https://m.media-amazon.com/images/I/81RHHnGydgL._SL1500_.jpg",
    sellerName: "RetailNet",
    isNewProduct: true,
  },
  {
    name: "Kamiliant by American Tourister Kiza Combo set of 3 Ash Blue Small, Medium and Large 4-wheel Check-in Suitcase",
    productId: "wwwwwwwww",
    brandName: "American Tourister",
    category: "Luggage",
    companyAssured: true,
    rating: "4",
    price: "20000",
    discount: "60%",
    imageURL: "https://m.media-amazon.com/images/I/81g+1znNgVL._UL1500_.jpg",
    sellerName: "RetailNet",
    isNewProduct: true,
  },
  {
    name: "pTron Bassbuds Wave ENC Bluetooth 5.3 Wireless Headphones, 40Hrs Total Playtime, Movie Mode & Deep Bass, Low Latency, Stereo Calls, Snug-fit TWS Earbuds, Smooth Touch Control & Type-C Charging (Grey)",
    productId: "vvvvvvvvvv",
    brandName: "pTron",
    category: "audio",
    companyAssured: true,
    rating: "3.9",
    price: "4000",
    discount: "45%",
    imageURL: "https://m.media-amazon.com/images/I/51V-P7alc0L._SL1100_.jpg",
    sellerName: "RetailNet",
    isNewProduct: true,
  },
  {
    name: "GoPro Hero 8 Black CHDHX-801 12 MP Action Camera",
    productId: "bbbwwwaaa",
    brandName: "GoPro",
    category: "electronics",
    companyAssured: true,
    rating: "3.9",
    price: "35000",
    discount: "20%",
    imageURL: "https://m.media-amazon.com/images/I/71UAtd5yS5L._SL1500_.jpg",
    sellerName: "RetailNet",
    isNewProduct: true,
  },
  // Similarly, you have to add minimum 10 products with the same fields.
  //you can use image from public directory or external-links
];
